title: Ken Horovatin's Explorations
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    bg_img: images/header-bg.jpg
    has_nav: true
    has_social: true
    logo_img: images/logo.png
    tagline: Exploring the world and ideas
    title: ''
  palette: yellow
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
